% Auto-generated by cameraCalibrator app on 26-Jul-2019
%-------------------------------------------------------

clc; clear all; close all;
% Define images to process
imageFileNames = {'D:\Personal\UW\BARC\Checker\Checker21_in\C1.bmp',...
    'D:\Personal\UW\BARC\Checker\Checker21_in\C2.bmp',...
    'D:\Personal\UW\BARC\Checker\Checker21_in\C3.bmp',...
    'D:\Personal\UW\BARC\Checker\Checker21_in\C6.bmp',...
    'D:\Personal\UW\BARC\Checker\Checker21_in\C7.bmp',...
    'D:\Personal\UW\BARC\Checker\Checker21_in\C8.bmp',...
    'D:\Personal\UW\BARC\Checker\Checker21_in\C9.bmp',...
    'D:\Personal\UW\BARC\Checker\Checker21_in\C14.bmp',...
    'D:\Personal\UW\BARC\Checker\Checker21_in\C15.bmp',...
    'D:\Personal\UW\BARC\Checker\Checker21_in\C18.bmp',...
    'D:\Personal\UW\BARC\Checker\Checker21_in\C19.bmp',...
    'D:\Personal\UW\BARC\Checker\Checker21_in\C20.bmp',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 6.770000e+00;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
%h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
%h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')

% save camera parameters for image undistortion
save('D:\Personal\UW\BARC\Checker\cameraParams_close.mat')