function [fitresult, gof] = TubeSplineSmoothing(Y, X)
%CREATEFIT(Y,X)
%  Create a fit.
%
%  Data for 'TubeSplineSmoothing' fit:
%      X Input : Y
%      Y Output: X
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-May-2019 16:32:35


%% Fit: 'TubeSplineSmoothing'.
[xData, yData] = prepareCurveData( Y, X );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.001;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts);

% Plot fit with data.
figure( 'Name', 'TubeSplineSmoothing' );
h = plot( fitresult, xData, yData );
legend( h, 'X vs. Y', 'TubeSplineSmoothing', 'Location', 'NorthEast' );
% Label axes
xlabel Y
ylabel X
grid on


