function [fitresult, gof] = createFit(Y1_1, X1_1)
%CREATEFIT(Y1_1,X1_1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Y1_1
%      Y Output: X1_1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Jul-2019 15:47:59


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Y1_1, X1_1 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'X1_1 vs. Y1_1', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Y1_1', 'Interpreter', 'none' );
ylabel( 'X1_1', 'Interpreter', 'none' );
grid on


